# -*- coding: utf-8 -*-
"""Lista de Números.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13bNGvXutKwfTJ643hZU6qrUHIRCu2Uyw
"""

# LISTAS EM PYTHON

numeros = [1, 3, 5, 7, 9]

#POSIÇÃO   1  2  3  4  5
#ÍNDICE    0  1  2  3  4

um = numeros [0]
tres = numeros [1]
cinco = numeros [2]
sete = numeros [3]
nove = numeros [4]

sete

cinco