# -*- coding: utf-8 -*-
"""Lista de Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10PqswM_JbLpKUF6Lyr8WTX0_KtBLSpCC
"""

# LISTAS EM PYTHON

lista_de_listas = [ [1,2] , [3,4] , [5,6]]
#POSIÇÃO               1        2     3
#ÍNDICE                0        1     2

primeira_sublista = lista_de_listas [0]
segunda_sublista = lista_de_listas [1]
terceira_sublista = lista_de_listas [2]

primeira_sublista

segunda_sublista

terceira_sublista

primeiro_numero = primeira_sublista [0]
segundo_numero = primeira_sublista [1]

primeiro_numero

segundo_numero

# É POSSÍVEL AINDA, ATRIBUIR VALORES AOS ELEMENTOS DA SEGUNDA E TERCEIRA SUBLISTAS.
